---
# tasks file for kerberos
- name: Copy krb5.conf
  shell: sudo mv -f ../kerberos/krb5.conf /etc/krb5.conf

- name: Set permissions on krb5.conf
  shell: sudo chmod 644 /etc/krb5.conf

- name: Initialize Kerberos Database
  shell: echo -e "mapr\nmapr\n" | sudo kdb5_util create -r EXAMPLE.COM -s

- name: Create Kerberos Principal
  shell: echo -e "addprinc mapr\nmapr\nmapr\nquit" | sudo kadmin.local

- name: Obtain Kerberos Ticket
  shell: echo -e "mapr\n" | kinit mapr


