---
# tasks file for kerberos
- name: Copy krb5.conf
  copy:
    src: ../kerberos/krb5.conf
    dest: /etc/krb5.conf

- name: Set permissions on krb5.conf
  file:
    path: /etc/krb5.conf
    mode: '0644'

- name: Initialize Kerberos Database
  shell: echo -e "mapr\nmapr\n" | sudo kdb5_util create -r EXAMPLE.COM -s

- name: Create Kerberos Principal
  shell: echo -e "addprinc mapr\nmapr\nmapr\nquit" | sudo kadmin.local

- name: Restart Kerberos Services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - krb5kdc
    - kadmin
  become: yes
  notify: Wait for Services

- name: Obtain Kerberos Ticket
  shell: echo -e "mapr" | kinit mapr


