---
# tasks file for kerberos
- name: Copy krb5.conf
  copy:
    src: ../kerberos/krb5.conf
    dest: /etc/krb5.conf

- name: Set permissions on krb5.conf
  file:
    path: /etc/krb5.conf
    mode: '0644'

- name: Initialize Kerberos Database
  shell: echo -e "mapr\nmapr\n" | kdb5_util create -r EXAMPLE.COM -s

- name: Create Kerberos Principal
  shell: echo -e "addprinc mapr\nmapr\nmapr\nquit" | sudo kadmin.local

- name: Obtain Kerberos Ticket
  shell: echo -e "mapr" | kinit mapr

- name: Restart kerberos services
  command: "systemctl restart krb5kdc kadmin"
