---
# tasks file for yum
- name: Install dialog
  yum:
    name: dialog
    state: latest
    disablerepo: MapR_Core,MapR_Ecosystem,MapR_Installer

- name: Install kerberos server
  yum:
    name: krb5-server
    state: latest
    disablerepo: MapR_Core,MapR_Ecosystem,MapR_Installer

- name: Install kerberos libraries
  yum:
    name: krb5-libs
    state: latest
    disablerepo: MapR_Core,MapR_Ecosystem,MapR_Installer

- name: Install kerberos workstation
  yum:
    name: krb5-workstation
    state: latest
    disablerepo: MapR_Core,MapR_Ecosystem,MapR_Installer
