---
- name: main playbook
  hosts: localhost
  become: true

  tasks:

  - name: install dialog
    yum:
      name: dialog
      state: latest
      disablerepo: MapR_Installer,MapR_Ecosystem,MapR_Core

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant"

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant/projet-jems"

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant/projet-jems/data"

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant/projet-jems/data/artist"

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant/projet-jems/data/museum"

  - name: Create HDFS Directory
    command: "hadoop dfs -mkdir /user/vagrant/projet-jems/data/work"
  
  - name: Copy csv to HDFS
    command: "hadoop dfs -put ../data/artist/artist.csv /user/vagrant/projet-jems/data/artist/artist.csv"

  - name: Copy csv to HDFS
    command: "hadoop dfs -put ../data/museum/museum.csv /user/vagrant/projet-jems/data/museum/museum.csv"

  - name: Copy csv to HDFS
    command: "hadoop dfs -put ../data/work/work.csv /user/vagrant/projet-jems/data/work/work.csv"