---
- name: main playbook
  hosts: localhost
  become: true

  tasks:

  - name: install display
    yum:
      name: display
      state: latest
      disablerepo: MapR_Installer,MapR_Ecosystem,MapR_Core