---
# vars file for maven
url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
filename: apache-maven-3.9.6-bin.tar.gz
foldername: apache-maven-3.9.6
new_foldername: maven-3.9.6
path: /opt/mapr/maven